language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update
  - sudo apt-get -y install wine1.8 winetricks

script:
  - yarn install
  - yarn build:prod
  - yarn dist:win
  
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: wonderful-app-nkj
  region: us-east-2
  skip_cleanup: true
  local_dir: dist
