matrix:
  include:
    - os: linux
      services: docker
      language: node_js
      node_js:
      - node

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    
install:
  - apt-get update
  - apt-get install wine

script:
  - yarn install
  - yarn build:prod
  - yarn dist:win
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
