dist: bionic
addons:
  apt:
    sources:
      - ppa:ubuntu-wine/ppa
    packages:
    - wine
language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - yarn install
  - yarn build:prod
  - yarn dist:win
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
