matrix:
  include:
    - os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - yarn install
  - yarn build:prod
  - yarn dist
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
