language: node_js
node_js:
  - node
cache:
  yarn: true
  wine: true
  directories:
    - node_modules
install:
  - sudo apt-get update
  - sudo apt-get -y install wine
script:
  - yarn build:prod
  - yarn dist:win
  - ls dist
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: wonderful-app-nkj
  region: us-east-2
  skip_cleanup: true
  local_dir: dist
branches:
  only:
    - master
