language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build:prod
  - yarn dist
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: wonderful-app-nkj
  region: us-east-2
  skip_cleanup: true
  local_dir: build
branches:
  only:
    - master
